default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
        language: python
        files: \.py$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=.:src:tests', --py36-plus]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--quiet]
-   repo: local
    hooks:
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG.rst|README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        files: ^(src/|tests/)
        args: []
        additional_dependencies:
          - boltons
          - ruff
          - click >=6.0
          - isort
          - tomli
